### ISSUE TITLE
Crush and Swipes

### ISSUE THREAD

**Issue by kfoau9h39** [benjaminsage/PageView#10]
```
iPages {
            ForEach(0..<10) {
                Text("Index \($0)")
            }
        }
```
Will swipe itself

and if I set array in forEach I get error: 

`Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444`

<img width="579" alt="Снимок экрана 2020-11-02 в 15 53 05" src="https://user-images.githubusercontent.com/56353323/97875723-80638a00-1d23-11eb-9baa-13ba40fd6e80.png">

**Comment by kfoau9h39** [comment]
Error reproduced when I set empty array. 

Why iPages swipes views itself?

**Comment by kfoau9h39** [comment]
iPages makes duplicates of views

**Comment by blsage** [comment]
Hi,

If you are talking about the unwanted animation that happens when the parent's state changes, that is now fixed. I tested your code, and it runs without bugs now.

Regarding your index out of bounds error, make sure not to programmatically change the pages binding to an out of bounds value. We discussed allowing out of bounds numbers as wrapping, but in the end decided it would cause more issues than fix them. If you would like this feature, let me know.

Also if you don't use your own `selection` binding, this shouldn't ever be an issue.

If you have any other code producing errors, definitely open more issues. Just let me know 😄
